### ISSUE TITLE
Shrink

### ISSUE THREAD

**Issue by lucasheilman** [jms44/EndangeredSpeciesPixelArt#1]
Why don't you use interpolation = cv2.INTER_AREA on the shrink resize?

**Comment by jms44** [comment]
On the resize where the image is being made smaller, I did not particularly care about which resize method was used as most methods would achieve an acceptably accurate value for the pixels in the smaller image. I allowed opencv to use the default interpolation method which is Inter-Linear. See [here](https://docs.opencv.org/2.4/modules/imgproc/doc/geometric_transformations.html#void%20resize(InputArray%20src,%20OutputArray%20dst,%20Size%20dsize,%20double%20fx,%20double%20fy,%20int%20interpolation)) for resize() documentation.

**Comment by lucasheilman** [comment]
I would recommend using INTER_AREA as it leads to a more accurate shrunk image by taking into account the surrounding pixels. OpenCV also recommends it when shrinking images see [here](https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_imgproc/py_geometric_transformations/py_geometric_transformations.html#scaling).

**Comment by jms44** [comment]
Thanks for the input. I had not considered the accuracy of the various interpolation methods for downsizing when creating this project. You are correct that INTER-AREA would have been a more accurate resize.
